# Generated by Django 4.1.13 on 2023-11-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='descriprion',
            new_name='description',
        ),
    ]
